#!/usr/bin/with-contenv bash

if [ -n "$VIRTUAL_HOST" ]; then
    KEY_NAME=$VIRTUAL_HOST
    sed -i "s/cert.crt/$VIRTUAL_HOST.crt/g" /config/nginx/site-confs/default
    sed -i "s/cert.key/$VIRTUAL_HOST.key/g" /config/nginx/site-confs/default
else
    KEY_NAME=cert
fi

SUBJECT="//C=US/ST=CA/L=Carlsbad/O=Linuxserver.io/OU=LSIO Server/CN=*"
if [[ -f /config/keys/${KEY_NAME}.key && -f /config/keys/${KEY_NAME}.crt ]]; then
    echo "using keys found in /config/keys"
else
    echo "generating self-signed keys in /config/keys, you can replace these with your own keys if required"
    openssl req -new -x509 -days 3650 -nodes -out /config/keys/${KEY_NAME}.crt -keyout /config/keys/${KEY_NAME}.key -subj "$SUBJECT"
fi

